FROM osrf/ros:noetic-desktop
# Install Ros Noetic
# RUN apt-get install -y ros-noetic-desktop-full
RUN apt-get update && apt-get install -y apt-utils git python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool \
build-essential ros-noetic-gazebo-ros-pkgs ros-noetic-gazebo-ros-control python3.pip ros-noetic-ros-control \
ros-noetic-ros-controllers && python3 -m pip install torch gymnasium stable-baselines3[extra] tensorboardX
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

# Check the last version in the repo:
ADD https://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:x-oauth-basic@api.github.com/repos/nicoRomeroCuruchet/SelfBalancingRobot/git/refs/heads/main version.json
RUN cd ~ && git clone -b main https://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@github.com/nicoRomeroCuruchet/SelfBalancingRobot.git
# Compile the robot enviroment
RUN /bin/bash -c '. /opt/ros/noetic/setup.bash; cd root/SelfBalancingRobot; catkin_make'
RUN echo "source  root/SelfBalancingRobot/devel/setup.bash" >> ~/.bashrc
# Compile the server
RUN /bin/bash -c "mkdir root/SelfBalancingRobot/src/scripts/env_cpp/build;"
RUN /bin/bash -c ". /opt/ros/noetic/setup.bash; cd root/SelfBalancingRobot/src/scripts/env_cpp/build; cmake ..; make"


#RUN echo "#!/bin/bash \n\
#    source /opt/ros/noetic/setup.bash \n\
#    roslaunch self_balancing_robot main.launch & \n\
#    sleep 5 & \n\
#    ./root/SelfBalancingRobot/src/scripts/env_cpp/build/robot_env &" > /ros_launch.sh && \
#    chmod +x /ros_launch.sh

#RUN /bin/bash -c 'sh ros_launch.sh'
#################################################################################################################################################
# BUILD AND RUN:                                                                                                                                #
# sudo docker build -t ros_noetic .                                                                                                             #
