FROM osrf/ros:noetic-desktop
# Install Ros Noetic
# RUN apt-get install -y ros-noetic-desktop-full
RUN apt-get update && apt-get install -y apt-utils git python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool \
build-essential ros-noetic-gazebo-ros-pkgs ros-noetic-gazebo-ros-control python3.pip ros-noetic-ros-control \
ros-noetic-ros-controllers && python3 -m pip install torch gymnasium stable-baselines3[extra] tensorboardX
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN pip install icecream loguru
# Check the last version in the repo:
ADD https://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:x-oauth-basic@api.github.com/repos/nicoRomeroCuruchet/SelfBalancingRobot/git/refs/heads/main version.json
RUN git clone -b main https://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@github.com/nicoRomeroCuruchet/SelfBalancingRobot.git
# Compile the robot enviroment
RUN /bin/bash -c '. /opt/ros/noetic/setup.bash; cd /SelfBalancingRobot; catkin_make'
RUN echo "source  /SelfBalancingRobot/devel/setup.bash" >> ~/.bashrc
# Compile the server
RUN /bin/bash -c "mkdir /SelfBalancingRobot/src/scripts/build;"
RUN /bin/bash -c ". /opt/ros/noetic/setup.bash; cd SelfBalancingRobot/src/scripts/build; cmake ..; make"

RUN echo "#!/bin/bash" > /ros_launch.sh && \
    echo "source /opt/ros/noetic/setup.bash" >> /ros_launch.sh && \
    echo "source /SelfBalancingRobot/devel/setup.bash" >> /ros_launch.sh && \
    echo "roslaunch self_balancing_robot main.launch gui:=true &" >> /ros_launch.sh && \
    echo "sleep 5" >> /ros_launch.sh && \
    echo "./SelfBalancingRobot/src/scripts/build/server_env &" >> /ros_launch.sh && \ 
    echo "python3 /SelfBalancingRobot/src/scripts/main.py -d train -m 1000 -t 100000 -o models/NEW_TRAINED_PPO_MODEL" >> /ros_launch.sh

RUN chmod +x /ros_launch.sh

#################################################################################################################################################
# BUILD AND RUN:                                                                                                                                #
# sudo docker build -t ros_noetic .                                                                                                             #
# sudo docker run --gpus all -i -v $(home)/runs:/phantomx/src/phantomx_training/scripts/runs -e prefix=server -t ros_noetic #
# sudo docker run --rm --name ros_noetic --gpus all -i -t ros_noetic /ros_launch.sh #
# Run with gui:
# sudo docker run -it --name ros_noetic --net=host -e DISPLAY -v /tmp/.X11-unix ros_noetic bash
#################################################################################################################################################

#################################################################################################################################################
## DELETE ALL CONTAINERS!!! sudo docker system prune -a                                                                                         #
#################################################################################################################################################
